export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const SIGNEDUP = 'SIGNEDUP';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';